#!/usr/bin/env perl

# LaTeXエンジンの設定
$latex      = 'uplatex %O -kanji=utf8 -no-guess-input-enc -synctex=1 -interaction=nonstopmode %S';
$pdflatex   = 'pdflatex %O -synctex=1 -interaction=nonstopmode %S';
$lualatex   = 'lualatex %O -synctex=1 -interaction=nonstopmode %S';
$xelatex    = 'xelatex %O -synctex=1 -interaction=nonstopmode %S';
$max_repeat = 5;

# 文献管理ツール
$biber      = 'biber %O --bblencoding=utf8 -u -U --output_safechars %B';
$bibtex     = 'bibtexu %O %B';

# 索引作成ツール
$makeindex  = 'upmendex %O -o %D %S';

# DVIからPDFへの変換
$dvipdf     = 'dvipdfmx %O -o %D %S';

# DVIからPSへの変換
if (`which convbkmk`) {
    $dvips = 'dvips %O -z -f %S | convbkmk -u > %D';
} else {
    $dvips = 'dvips %O -f %S > %D';
}

# ps2pdfの設定（Windowsの場合はGhostscriptを使用）
if ($^O eq 'MSWin32') {
    $ps2pdf = 'gswin64c -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=%D %O %S';
} else {
    $ps2pdf = 'ps2pdf %O %S %D';
}

# $pdf_mode = 0; PDF を作成しない。
# $pdf_mode = 1; $pdflatex を利用して PDF を作成。
# $pdf_mode = 2; $ps2pdf を利用して .ps ファイルから PDF を作成。
# $pdf_mode = 3; $dvipdf を利用して .dvi ファイルから PDF を作成。
# $pdf_mode = 4; $lualatex を利用して PDF を作成。
# $pdf_mode = 5; $xelatex を利用して PDF を作成。
$pdf_mode = 4;

# 一時ファイルの拡張子
@generated_exts = qw(aux bbl blg idx ilg ind lof log lot out toc fls fdb_latexmk synctex.gz);

# エラー時の処理
$failure_cmd = "echo Compilation failed";

# 詳細なログの取得
$diagnostics = 1;

# PDFビューアの設定
$preview_continuous_mode = 0;
$pvc_view_file_via_temporary = 0;
#$pdf_previewer = "";
if ($^O eq 'MSWin32') {
    if (-f 'C:/Program Files/SumatraPDF/SumatraPDF.exe') {
        $pdf_previewer = "\"C:/Program Files/SumatraPDF/SumatraPDF.exe\" -reuse-instance %S";
    } elsif (-f 'C:/Program Files (x86)/SumatraPDF/SumatraPDF.exe') {
        $pdf_previewer = "\"C:/Program Files (x86)/SumatraPDF/SumatraPDF.exe\" -reuse-instance %S";
    } else {
        $pdf_previewer = 'texworks %S';
    }
} elsif ($^O eq 'darwin') {
    if (-d '/Applications/Skim.app') {
        $pdf_previewer = 'open -ga /Applications/Skim.app %S';
    } else {
        $pdf_previewer = 'open %S';
    }
} else {
    $pdf_previewer = 'xdg-open %S';
}

# 一時ファイルのクリーンアップコマンド
add_cus_dep('clean', '', 0, sub {
    system("latexmk -c");
});

